### ISSUE TITLE
I try to test on this but it does not work.

### ISSUE THREAD

**Issue by a0fzide** [luisdemarchi/cordova-sample-facedetection#1]
![IMG_2543](https://user-images.githubusercontent.com/11240980/67934756-12115680-fbfb-11e9-87df-379ded752cb8.JPG)

build screen after clone

**Comment by luisdemarchi** [comment]
@a0fzide hi. Did the console have any errors? Can you check if the app has permission to open the camera?

**Comment by a0fzide** [comment]
@luisdemarchi Solve with check perrmission. Thanks
